### ISSUE TITLE
nothing after signup

### ISSUE THREAD

**Issue by justinvforvendetta** [countable/dogelet#2]
after clicking sign up, i just get a "click to go back button" and the rest of the page is blank.

127.0.0.1:3000/signup?email=123%40123.com&x=172&y=74

**Comment by justinvforvendetta** [comment]
any ideas? @countable @ChetanBhasin

**Comment by justinvforvendetta** [comment]
happens when i use my real email address as well. nothing shows up in my email, nor in spam folder.

**Comment by countable** [comment]
I'm guessing you need a mail server set up and added to your config?

**Comment by justinvforvendetta** [comment]
i added sendmail and sendgrid.. and i put the user name/pass in the config..

**Comment by justinvforvendetta** [comment]
console doesnt say anything other than 
GET /signup?email=123%40gmail.com&x=242&y=123 200 521ms - 499b

**Comment by justinvforvendetta** [comment]
i removed the sendmail and sendgrid i was using and installed postfix, and thats working, so i guess ill work on sendmail/sendgrid again

**Comment by justinvforvendetta** [comment]
got it =] set up heirloom and sendmail/sendgrid.
